// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzB42z46Re7p9pEv7jaD83HDYzYLhM9Yo',
    appId: '1:41149284653:android:11c954cc15bd02b26a93a4',
    messagingSenderId: '41149284653',
    projectId: 'yatmadf-6f014',
    storageBucket: 'yatmadf-6f014.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBafjUIitHvYf5qLDDfYcXc0_gLWfx-TBo',
    appId: '1:41149284653:ios:52b7c2d933b137d76a93a4',
    messagingSenderId: '41149284653',
    projectId: 'yatmadf-6f014',
    storageBucket: 'yatmadf-6f014.appspot.com',
    androidClientId: '41149284653-6t28kacq72gc6rt3tu5uk47g3gulflkm.apps.googleusercontent.com',
    iosClientId: '41149284653-ospf4g1ud8o8vf5hna3frpuc9covkf26.apps.googleusercontent.com',
    iosBundleId: 'naol.chala.firebaseTest',
  );
}
